
export default function SelectQarea({setShaikhToggle,setNameShaikh,setShaikhSound,ChangeUrlWithoutReload,nameSora,setMute,setPlay}:
  {
    setShaikhToggle:React.Dispatch<React.SetStateAction<boolean>>,
    setNameShaikh:React.Dispatch<React.SetStateAction<string>>,
    setShaikhSound:React.Dispatch<React.SetStateAction<string|null>>,
    setMute:React.Dispatch<React.SetStateAction<boolean>>,
    setPlay:React.Dispatch<React.SetStateAction<boolean>>,
    ChangeUrlWithoutReload:(qaree:string , sora:string)=>void,
    nameSora:string
  }
) {
  return (
        <>
       
{/* title classtitle="> */}
    <div className="overflow-y-scroll scrollbar-hide flex flex-col justify-start items-start px-2 absolute top-[100%] z-40 left-0 w-fit max-h-[400px] bg-gray-600 text-red-500">
    <span className="group-hafs text-white" >مرتل رواية حفص عن عاصم الكوفي</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="128kb____--mp3-------full-----quran----6236---ayaat-----__verse--by---verse---"  >المنشاوي - مرتل </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="full---moshaf----128kb---mp3------------quran----6236---ayaat-----__verse--by-"  >المنشاوي-المعلم</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236_____________full-quran-6236-ayah-by--alhosary--morattal--mad-almonfasel-e"  >الحصري - مرتل</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="64kb-alhosary-qasr-almonfasel-radio-6236-ayah"  >الحصري-الإذاعة</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="192kb----morattal----quran----6236---ayaat-----__verse--by---verse----_-by--ab_525"  >عبدالباسط - مرتل</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236-full-quran-6236-ayah-by--albanna--morattal---every-sorah-in-folder-114-file"  >محمود علي البنا - مرتل  </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="128kb_202210"  >مصطفى إسماعيل</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="128kb---a7mad--n3ena3---morattal------quran----6236---ayaat-----__verse--by---_189"  > أحمد نعينع </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="64kb__---mp3------------quran----6236---ayaat-----__verse--by---verse----_-by-"  >    محمد محمود الطبلاوي </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236-full-quran-6236-ayah-by--sa3d-alghamdy--every-sorah-in-folder-114-file"  >سعد الغامدي</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236--aya---ayat---128kb---naser--alqetamy--by--verse--by--verse---full---mosh"  > ناصر القطامي </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236--aya---ayat---128kb--yaser--aldosry--by--verse--by--verse---full---moshaf"  >  ياسر الدوسري </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236__full-quran-6236-ayah-by-maher-alm3eaqly---every-sorah-in-folder-114-file"  >  ماهر المعيقلي </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236--aya---ayat---64kb--fares--abbad--_--by--verse--by--verse---full---moshaf"  >  فارس عبّاد</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236-full-quran-6236-ayah-by--mshari-al3afasi--every-sorah-in-folder-114-file"  >مشاري راشد </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236__full-quran-6236-ayah-by--mohammad-ayyoob---every-sorah-in-folder-114-file"  > محمد أيوب </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="64kb-quran----6236---ayaat-----__verse--by---verse----_-by--mohammad----gebree"  >    محمد جبريل </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="KORAN-6236-full-quran-6236-ayah-by--ALSHOREAM--every-sorah-in-folder-114-file"  >سعود الشريم </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="192------kb---mp3------------quran----6236---ayaat-----__verse--by---verse----"  >عبدالرحمن السديسي </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="128kb--quran----6236---ayaat-----__verse--by---verse----_-by--alhozifi-------f_443"  > الحذيفي </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="MP3--6236-full-quran-6236-ayah-by--ALSHATERY---every-sorah-in-folder-114-file"  >أبوبكر الشاطري </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="192kb---quran----6236---ayaat-----__verse--by---verse----_-by--abd--amuhsin--a_353"  >عبدالمحسن القاسم </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="128kb--al3agamy------128----kb---mp3------------quran----6236---ayaat-----__ve"  > أحمد العجمي </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="way2sona_20160428_2029"  >ياسر سلامة </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="MP3--6236-full-quran-6236-ayah-by--SLAA7-ALHASHEM----every-sorah-in-folder-114"  > صلاح الهاشم </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236--aya---ayat---128kb---akram--al3alaqmy---by--verse--by--verse---full---mo"  > أكرم العلاقمي </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236--ayah--ayat---mp3-------192kb---hany--alrefa3y-----quran----6236---ayaat-"  > هاني الرفاعي </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="128kb___--by---aly--7ajjaj---alseweasy----quran----6236---ayaat-----__verse--b"  > علي حجاج السويسى </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236-full-quran-6236-ayah-by-ebraheem-alakhdar---every-sorah-in-folder-114-file"  > إبراهيم الأخضر </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236--_-_aya----ayat---64kb--khalifa--alteneagy---moratal---by--verse--by--ver"  >خليفة الطنيجي </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="full-quran-6236-ayah-by--abd-allah-almatrood-128kb--verse-by-verse"  >عبدالله المطرود </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="114sora-6236-ayah-by-mohammad-abd-alkareem"  >محمد عبدالكريم </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="48kb--quran----6236---ayaat-----_-_verse--by---verse----_-by--shehraiar--ber"  >شهريار بهريز </span>
      <span className="group-hafs text-white" >مجود رواية حفص عن عاصم الكوفي</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236-full-quran-6236-ayah-by--alminshawi-mogawwad-192kb--verse-by-verse"  >المنشاوي - مجود</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="full-quran-6236-ayah-by--alhosary-mogawwad--128kb--verse-by-verse"  >الحصري - مجود  </span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="alfirdwsiy2018_gmav_201807"  >عبدالباسط - مجود</span>
      <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="192kb-------mogawwad-------quran----6236---ayaat-----__verse--by---verse----_-_268"  >عبدالله بصفر-مجود </span>
    
  <span className="group-warsh text-white" >رواية ورش عن نافع المدني</span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="alhosary---warsh---64kb----full--ayat--6236--aya"  >الحصري-ورش</span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="128kb----6236--ayah---quran-128"  >عبدالباسط -ورش</span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="128kb---mp3------------quran----6236---ayaat-----__verse--by---verse----_-by--_382"  > سهل ياسين-ورش </span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="3568563568356835683568568_002"  >    الجزائري - ورش</span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="6236--aya---ayat---128kb---ibraheem---aldosry--by---warsh---by--verse--by--ver"  > إبراهيم الدوسري-ورش</span>
  
  <span className="group-qalon text-white" >رواية قالون عن نافع المدني</span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="32kb-alhosary-qaloon-ayat-full-6236-aya"  >الحصري - قالون</span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="96kb--quran--by--alhozifi--by--qaloon---6236---ayaat-----__verse--by---verse--"  >الحذيفي-قالون  </span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="128kb--quran--ahmad--khedr--altrabolsy---by---qaloon-----6236---ayaat-----__ve"  >أحمد خضر الطرابلسي-قالون  </span>
  
  <span className="group-shuba text-white" >رواية شعبة عن عاصم الكوفي</span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="alhozaifi__by__shoa3bah__56kb___ayat__6236_ayah__full"  >الحذيفي-شعبة  </span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="96kb--quran--by--foad--alkhamry---by--sho3bah--6236---ayaat-----__verse--by---"  >فؤاد الخامري -شعبة  </span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="alfirdwsiy1433_gmai555555555555555555555555555555hhhhhhhhhhhhhhh"  >عبدالحكيم عبداللطيف -شعبة  </span>
  
  <span className="group-susi text-white" >رواية السوسي عن أبي عمرو</span>
    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="245745247247247247247247457y__96kb/full--quran--6236-aya--by--soofy_by__soosy__96kb.zip"  > عبدالرشيد صوفي-السوسي  </span>
 
  <span className="group-duri text-white" >رواية الدوري عن أبي عمرو</span>

    <span className="hover:bg-blue-700 hover:text-white px-2 py-1 rounded w-full text-end" onClick={(e)=>{setShaikhToggle(false);setNameShaikh((e.target as unknown as HTMLElement).innerText);setMute(true);setPlay(true);setShaikhSound((e.target as unknown as HTMLElement).getAttribute('title'));ChangeUrlWithoutReload((e.target as unknown as HTMLElement).innerText,nameSora)}} title="96kb___--quran--by---mefta7--alsaltany--by--aldory--an---aby---amr-----6236---"  >مفتاح السلطني -الدوري </span>
 
  </div>
        </>
  )
}
